### PR TITLE
Update Kata.php

### PR DESCRIPTION
**Pull request by simodima**

### CODE REVIEW

**Comment by leopro** [comment]
@toretto460 you are proposing to start with a red test?

**Comment by simodima** [comment]
A red test could be the starting point :-)
(According to the TDD mantra red/green/refactor)

**Comment by leopro** [comment]
Yes, generally you're right.
In this case I'm using the first test just to check that setup was done.

For this kata I would not give tests that must be satisfied ;-)

**Comment by leopro** [comment]
I updated the readme, giving the starting context.

**Pull request closed without merging**
